### ISSUE TITLE
[Support] Recommended approach when MyVendor#perform_resolution is long-running

### ISSUE THREAD

**Issue by patcon** [18F/identity-proofer-gem#3]
https://github.com/18F/identity-proofer-gem/blob/master/lib/proofer/vendor/mock.rb#L36-L44

I'm planning to create a custom proofer that will run against a RESTful (ish) API that itself uses a task queue:
http://can-ereg-api.herokuapp.com/

I suspect it will take about 45 seconds to get a resolution (although this could perhaps be improved to get it down to 10 seconds).

Any recommended approach here? Will using a blocking bit of logic here break any assumptions that you folks have made about how proofing vendors will work? Any tips appreciated!

Thanks!

**Comment by pkarman** [comment]
There's no assumption in this gem about how long the proofer might take to resolve, or whether it happens in an async queue or sync via direct browser request. What's really the issue is the UX while the user is waiting. If you throw the proofing job in a background queue, you have to handle the UX differently than identity-idp does currently. The current assumption is that the proofing process happens Quickly Enough that there is no need to provide any custom UX (page mask, spinning ball, polling, etc). We may change that based on real world experience.

**Comment by patcon** [comment]
Thanks Peter :) I'll sort through it and open another issue if I start trooping away on something. re: ux.
